apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: configure-secrets-task
spec:
  serviceAccountName: tekton-secrets-sa
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl get pods
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: private-git-repos
          annotations:
            tekton.dev/git-0: https://github.com # Described below
        type: kubernetes.io/basic-auth
        stringData:
          username: stamuser
          password: stampass
        EOF
  workspaces:
    - name: manifest-dir
      secret:
        secretName: my-aws-secret