apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: configure-git-ssh-secrets-task
spec:
  serviceAccountName: tekton-secrets-sa
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl get secret
        ls -la
        sleep 1

        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        type: kubernetes.io/ssh-auth
        data:
          config: $(cat config | base64  -w 0)
          known_hosts: $(cat known_hosts_github | base64  -w 0)
          ssh-privatekey: $(cat id_rsa | base64  -w 0)
        kind: Secret
        metadata:
          creationTimestamp: null
          name: ssh-key-secret
          annotations:
            tekton.dev/git-0: github.com # Described below
        EOF
  
  workspaces:
    - name: manifest-dir
      secret:
        secretName: ssh-secret
