apiVersion: v1
type: kubernetes.io/ssh-auth
data:
  config: <base64 -w 0>
  known_hosts: <base64 -w 0>
  ssh-privatekey: <base64 -w 0>
kind: Secret
metadata:
  creationTimestamp: null
  name: ssh-key-secret
  annotations:
    tekton.dev/git-0: github.com # Described below
