apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-secrets-sa
secrets:
  - name: my-aws-secret

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-secrets-sa-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "delete", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-secrets-sa-rb
subjects:
  - kind: ServiceAccount
    name: tekton-secrets-sa
roleRef:
  kind: Role
  name: tekton-secrets-sa-role
  apiGroup: rbac.authorization.k8s.io
---