apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:      
      - data:
        - key: config
          objectName: "tekton_ssh_config_yossi"
        - key: ssh-privatekey
          objectName: "tekton_ssh_id_rsa_yossic"
        - key: known_hosts_github
          objectName: "tekton_ssh_known_hosts_github_yossic"
        type: kubernetes.io/ssh-auth
        secretName: ssh-secret-type
  parameters:
    objects: | 
        - objectName: "/default/production_qa/otel_exporter_otlp_endpoint"
          objectType: "ssmparameter"
          objectAlias: "otel_exporter_endpoint"
        - objectName: "tekton_ssh_config_yossi"
          objectType: "secretsmanager"
        - objectName: "tekton_ssh_id_rsa_yossic"
          objectType: "secretsmanager"
        - objectName: "tekton_ssh_known_hosts_github_yossic"
          objectType: "secretsmanager"



---

kind: Pod
apiVersion: v1
metadata:
  name: nginx-deployment
spec:
  serviceAccountName: nginx-deployment-sa
  containers:
    - image: nginx
      name: nginx
      imagePullPolicy: Never
      # env:
      #   - name: tekton_ssh_config_yossi
      #     valueFrom:
      #       secretKeyRef:
      #         name: ssh-key-secret
      #         key: config
      volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets"