apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:      
      - data:
        - key: config
          objectName: "tekton_ssh_config_yossi"
        - key: id_rsa
          objectName: "tekton_ssh_id_rsa_yossic"
        - key: known_hosts_github
          objectName: "tekton_ssh_known_hosts_github_yossic"
        secretName: ssh-secret
      - data:
        - key: config
          objectName: "tekton_ssh_config_yossi"
        - key: id_rsa
          objectName: "tekton_ssh_id_rsa_yossic"
        - key: known_hosts_github
          objectName: "tekton_ssh_known_hosts_github_yossic"
        type: kubernetes.io/ssh-auth
        secretName: ssh-secret-type

      - data:
        - key: my-secret2
          objectName: my-secret2  # reference the corresponding parameter
        - key: OTEL_EXPORTER
          objectName: "myssm"  # reference the corresponding parameter
        
        type: Opaque
        secretName: ssh-secret
  parameters:
    objects: | 
        - objectName: "MySecret"
          objectType: "secretsmanager" 
        - objectName: "/default/production_qa/otel_exporter_otlp_endpoint"
          objectType: "ssmparameter"
          objectAlias: "myssm"
        - objectName: "tekton_github_username"
          objectType: "secretsmanager"
        - objectName: "tekton_github_password"
          objectType: "secretsmanager"
        - objectName: "tekton_ssh_config_yossi"
          objectType: "secretsmanager"
        - objectName: "tekton_ssh_id_rsa_yossic"
          objectType: "secretsmanager"
        - objectName: "tekton_ssh_known_hosts_github_yossic"
          objectType: "secretsmanager"
